site_name: drf-pyseto
site_description: Simple PASETO (v4.local) authentication for Django REST Framework.
site_url: https://p-r-a-v-i-n.github.io/drf-pyseto/
repo_name: p-r-a-v-i-n/drf-pyseto
repo_url: https://github.com/p-r-a-v-i-n/drf-pyseto

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - API Endpoints: endpoints.md
  - Settings: settings.md
  - Customizing: customizing.md
